apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dep
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-dep 

  template:
    metadata:
      labels:
        app: hello-dep
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/seventh-magnet-407805/garkiran1/jenapp1:mynginx
        imagePullPolicy: Always
        name: jenapp1
        ports:
        - containerPort: 8080
